import { Icon } from 'antd'

export default {
  // 事项类别
  mattersType: [{
    icon: <Icon type="menu" />,
    name: '全　　部',
    count: 0,
  }, {
    icon: <Icon type="money-collect" />,
    name: '参保征缴',
    count: 1,
    list: [{
      name: '个体劳动者(灵活就业人员)参保登记',
      recommend: true,
      describe: '灵活就业参保',
      businessType: '30A225',
      path: 'aNewGTLDZCBDJ.html',
      type: 'A01'
    }, {
      name: '个体劳动者(灵活就业人员)参保信息变更登记',
      describe: '灵活就业参保信息变更',
      path: 'aNewGTLDZCBDJBG.html',
      businessType: '30A210_1',
      type: 'A02'
    }, {
      name: '社会保险职工参保信息变更登记',
      recommend: true,
      describe: '个人基本信息变更',
      type: 'A03',
      businessType: '30A210',
      path: 'aNewSHBXCBBGDJ.html',
    }, {
      name: '城乡居民基本养老保险参保登记',
      describe: '城乡居民参保',
      type: 'A04',
      businessType: '30A208',
      path: 'aNewCXJMJBYLDJ.html'
    }, {
      name: '企业职工基本养老保险关系转移',
      recommend: true,
      describe: '企业职工基本养老保险关系转移',
      businessType: '30A407',
      path: 'aNewJBYLZY.html',
      type: 'A05',
      closed: true,
      closedDesc: '该事项暂未开放'
    }, {
      name: '企业职工基本养老保险关系接续',
      recommend: true,
      describe: '企业职工基本养老保险关系接续',
      path: 'aNewQYZGYLJX.html',
      type: 'A06',
      businessType: '30A408',
      closed: false,
      closedDesc: '该事项暂未开放'
    }, {
      name: '基本养老保险跨制度转移衔接',
      describe: '基本养老保险跨制度转移衔接',
      businessType: '30A426',
      path: 'aNewKZDZYXJ.html',
      type: 'A07',
      closed: false,
      closedDesc: '该事项暂未开放'
    }, {
      name: '个体劳动者(灵活就业人员)停保登记',
      describe: '灵活就业停保登记',
      businessType: '30A222',
      path: 'aNewGTLDZTB.html',
      type: 'A08'
    }, {
      name: '城乡居民基本养老保险参保信息变更登记',
      describe: '城乡参保信息变更',
      businessType: '30A210_2',
      path: 'aNewCXJMYLCBDJ.html',
      type: 'A11'
    }, {
      name: '军人退役基本养老保险关系接续',
      describe: '军人退役基本养老保险关系接续',
      businessType: '30A413',
      path: 'aNewJRTYYLBXJX.html',
      type: 'A13',
      closed: false,
      closedDesc: '该事项暂未开放'
    }]
  }, {
    icon: <Icon type="insurance" />,
    name: '养老待遇',
    count: 2,
    list: [
      {
        name: '城乡居民基本养老保险待遇核准支付',
        describe: '城乡养老待遇申领',
        businessType: '30I801',
        TcqType: '1',
        path: 'aNewCXYLBXDYZF.html',
        type: 'B01'
      }, {
        name: '劳模退休时一次性补贴资格确认',
        describe: '劳模退休时一次性补贴资格确认',
        businessType: '30I106',
        path: 'aNewLmtx.html',
        type: 'B02',
        TcqType: '1',
        closed: false,
        closedDesc: '该事项暂未开放'
      }, {
        name: '达到法定退休年龄前终止职工基本养老保险关系待遇核准支付',
        describe: '个人账户一次性待遇申领',
        businessType: '30A412',
        path: 'aNewCGDJHZZF.html',
        type: 'B03',
        finishType: '6402',
        closed: true,
        closedDesc: '该事项暂未开放'
      }, {
        name: '特殊工种提前退休核准',
        describe: '职工提前退休(退职)申请',
        path: 'aNewTSGZTQTX.html',
        businessType: '30I103',
        type: 'B06',
        closed: false,
        closedDesc: '该事项暂未开放'
      }, {
        name: '新增退休人员养老保险待遇核准支付',
        recommend: true,
        describe: '养老保险待遇核准支付',
        path: 'aNewXZTXYLBX.html',
        businessType: '30I201',
        type: 'B07'
      }, {
        name: '离退休人员死亡待遇核准支付',
        describe: '离退休人员死亡待遇核准支付',
        businessType: '30I303',
        path: 'aNewLTXSW.html',
        type: 'B08',
        TcqType: '1',
        closed: false,
        closedDesc: '该事项暂未开放'
      }, {
        name: '高级专家退休时一次性补贴资格确认',
        describe: '高级专家退休时一次性补贴资格确认',
        businessType: '30I107',
        path: 'aNewGJZJTXBTQR.html',
        type: 'B10',
        closed: false,
        closedDesc: '该事项暂未开放'
      }, {
        name: '因病或非因工致残完全丧失劳动能力提前退休(退职)核准',
        describe: '提前退休(退职)核准',
        businessType: '30I104',
        path: 'aNewYBSSLDNLTX.html',
        type: 'B11',
        closed: false,
        closedDesc: '该事项暂未开放'
      }, {
        name: '参保人员死亡遗属生活困难补助费核准支付',
        describe: '死亡遗属补助费核准支付',
        businessType: '30I402',
        path: 'aNewCBRYSWYSBZZF.html',
        type: 'B12',
        closed: false,
        closedDesc: '该事项暂未开放'
      }, {
        name: '申请补缴城乡居民基本养老保险费',
        describe: '补缴城乡基本养老保险费',
        businessType: '30A302',
        path: 'aNewSQBJYLBXF.html',
        type: 'B13',
        closed: false,
        closedDesc: '该事项暂未开放'
      },
      {
        name: '达到法定退休年龄领取基本养老保险资格确认',
        describe: '退休领取基本养老保险资格确认',
        businessType: '30I102',
        path: 'aNewDDFDTXZGQR.html',
        type: 'B14',
        TcqType: '1'
      },
    ]
  }, {
    icon: <Icon type="fork" />,
    name: '工伤待遇',
    count: 3,
    list: [
      {
        name: '工伤保险医疗待遇核准支付',
        describe: '工伤医疗(康复)费用申报',
        businessType: '30L301',
        path: 'aNewGSBXYLZF.html',
        type: 'C01',
        closed: false,
        closedDesc: '该事项系统维护中'
      }, {
        name: '工伤保险伤残一次性待遇核准支付',
        describe: '伤残待遇申领',
        businessType: '30L302',
        path: 'aNewGSBXSCDYZF.html',
        TcqType: '1',
        type: 'C02',
        closed: false,
        closedDesc: '该事项系统维护中'
      }, {
        name: '工伤保险一次性医疗补助金核准支付',
        describe: '一次性工伤医疗补助金申请',
        businessType: '30L307',
        path: 'aNewONCEYLHZZF.html',
        type: 'C03',
        closed: false,
        closedDesc: '该事项系统维护中'
      }, {
        name: '工伤保险伤残定期待遇核准支付',
        describe: '辅助器具配置(更换)费用申报',
        businessType: '30L303',
        path: 'aNewGSBXSCDQZF.html',
        type: 'C04',
        closed: false,
        closedDesc: '该事项暂未开放'
      }, {
        name: '工伤保险辅助器具更换核准支付',
        describe: '工伤保险辅助器具更换核准支付',
        businessType: '30L305',
        path: 'aNewGSBXFZQJGHZF.html',
        type: 'C05',
        closed: false,
        closedDesc: '该事项暂未开放'
      }, {
        name: '工伤保险辅助器具配置核准支付',
        describe: '工伤保险辅助器具配置核准支付',
        businessType: '30L306',
        path: 'aNewGSBXFZQJPZZF.html',
        type: 'C06',
        closed: false,
        closedDesc: '该事项暂未开放'
      }, {
        name: '工伤保险统筹地区以外就医交通费、食宿费核准支付',
        describe: '统筹地区以外交通、食宿费申领',
        businessType: '30L308',
        path: 'aNewGSBXTCQW.html',
        TcqType: '1',
        type: 'C07',
        closed: false,
        closedDesc: '该事项暂未开放'
      }, {
        name: '工伤保险定期待遇暂停或终止',
        describe: '工伤保险待遇变更',
        businessType: '30L402',
        path: 'aNewGSBXDQDYZT.html',
        TcqType: '1',
        type: 'C08',
        closed: false,
        closedDesc: '该事项暂未开放'
      }, {
        name: '工亡职工一次性待遇核准支付',
        describe: '工亡职工一次性待遇核准支付',
        businessType: '30L304',
        path: 'aNewGWZGYCX.html',
        TcqType: '1',
        type: 'C09',
        closed: false,
        closedDesc: '该事项暂未开放'
      }, {
        name: '工亡职工供养亲属待遇核准支付',
        describe: '供养亲属抚恤金申领',
        businessType: '30L314',
        path: 'aNewGWZGGYQS.html',
        TcqType: '1',
        type: 'C10',
        closed: false,
        closedDesc: '该事项暂未开放'
      }
    ]
  }, {
    icon: <Icon type="search" />,
    name: '查　　询',
    count: 4,
    list: [
      {
        name: '参保人员查询打印社会保险信息',
        recommend: true,
        describe: '个人权益记录查询打印',
        path: 'aNewCBRYDY.html',
        businessType: 'cxdy',
        model: '97',
        type: 'D01'
      }, {
        name: '缴费信息查询',
        describe: '缴费信息查询',
        businessType: 'JFXXCX',
        model: '98',
        path: 'aNewJFXXCX.html',
        type: 'D02'
      }, {
        name: '工伤查询',
        describe: '工伤查询',
        businessType: '30L121',
        path: 'aNewINJURYCX.html',
        type: 'D03',
        closed: false,
        closedDesc: '该事项暂未开放'
      }, {
        name: '退休待遇查询',
        describe: '退休待遇查询',
        businessType: 'TXDYCX',
        path: 'aNewTXDYCX.html',
        model: '100',
        type: 'D04'
      },
    ]
  }, {
    icon: <Icon type="file-text" />,
    name: '证明待遇',
    count: 5,
    list: [
      {
        name: '个人保险参保证明',
        describe: '个人保险参保证明',
        path: '',
        type: 'E01',
        model: '1'
      }, {
        name: '基本养老转移凭证',
        describe: '基本养老转移凭证',
        path: '',
        type: 'E02',
        model: '7',
        closed: false,
        closedDesc: '该事项暂未开放'
      }, {
        name: '基本养老历年参保证明',
        describe: '基本养老历年参保证明',
        path: '',
        type: 'E04',
        model: '2'
      }, {
        name: '养老保险待遇发放证明',
        describe: '养老保险待遇发放证明',
        path: '',
        type: 'E05',
        model: '3'
      }, {
        name: '工伤认定书查询打印',
        describe: '工伤认定书查询打印',
        path: '',
        type: 'E06',
        model: '99',
        closed: false,
        closedDesc: '该事项暂未开放'
      },
    ]
  }]
}